### ISSUE TITLE
base目录有问题

### ISSUE THREAD

**Issue by wuleijun** [lyimin/beautifulApp#1]
项目路径显示
beautifulApp/BeautifulApp/BeautifulApp/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/Base/Class/

**Comment by lyimin** [comment]
你好，请问是在哪里显示这个问题？

**Comment by lyimin** [comment]
你好，请问是在哪里显示这个问题？

**Comment by wuleijun** [comment]
https://github.com/lyimin/beautifulApp/tree/master/BeautifulApp/BeautifulApp/Class/Base
看目录 @lyimin

**Comment by lyimin** [comment]
好的，马上处理，谢谢
